import { dirname, join, relative } from "node:path";

export interface GeneratedImportFile {
  path: string;
  content: string;
  managed: boolean;
}

export interface ImportCodegenInput {
  cwd: string;
  projectName: string;
  packageName: string;
  modelsEntryPath: string;
  configPath: string;
  modelsVersion: string;
  contentTypes: Record<string, any>[];
  globalFields: Record<string, any>[];
  isMonorepo?: boolean | undefined;
}

export interface ImportCodegenResult {
  files: GeneratedImportFile[];
  managedFiles: string[];
  contentTypeUids: string[];
  globalFieldUids: string[];
}

const GENERATED_HEADER = "// Generated by csdx stacksmith:import. Manual edits may be overwritten.\n\n";

const titleFromUid = (uid: string): string =>
  uid
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");

const toKebabCase = (value: string): string => value.replaceAll("_", "-");

type Node =
  | { kind: "raw"; value: string }
  | { kind: "json"; value: unknown }
  | { kind: "object"; entries: Array<{ key: string; value: Node }> }
  | { kind: "array"; items: Node[] }
  | { kind: "call"; name: string; uid: string; options?: Node | undefined; comment?: string | undefined };

const INDENT = 2;
const pad = (columns: number): string => " ".repeat(columns);

const raw = (value: string): Node => ({ kind: "raw", value });
const jsonNode = (value: unknown): Node => ({ kind: "json", value });
const objectNode = (entries: Array<{ key: string; value: Node }>): Node => ({ kind: "object", entries });
const arrayNode = (items: Node[]): Node => ({ kind: "array", items });

/**
 * Convention for `format(node, indent)`:
 * - Returns a string whose first line has NO leading whitespace (the caller
 *   places it wherever).
 * - For multi-line outputs, subsequent lines have absolute indentation
 *   relative to column 0, assuming the first character lands at column `indent`.
 * - The closing bracket of a multi-line block sits at column `indent`.
 *
 * Embedding a multi-line child value in `${pad}${key}: ${valueStr}` works
 * because the child's subsequent lines are already absolute — we only prepend
 * the parent's pad to the first line via string concatenation.
 */
const format = (node: Node, indent: number): string => {
  switch (node.kind) {
    case "raw":
      return node.value;
    case "json": {
      const serialized = JSON.stringify(node.value, null, INDENT);
      if (!serialized.includes("\n")) return serialized;
      const [first, ...rest] = serialized.split("\n");
      return [first, ...rest.map((line) => `${pad(indent)}${line}`)].join("\n");
    }
    case "object": {
      if (node.entries.length === 0) return "{}";
      const inner = indent + INDENT;
      const lines: string[] = ["{"];
      for (const { key, value } of node.entries) {
        const valueStr = format(value, inner);
        lines.push(`${pad(inner)}${key}: ${valueStr},`);
      }
      lines.push(`${pad(indent)}}`);
      return lines.join("\n");
    }
    case "array": {
      if (node.items.length === 0) return "[]";
      const inner = indent + INDENT;
      const lines: string[] = ["["];
      for (const item of node.items) {
        const itemStr = format(item, inner);
        lines.push(`${pad(inner)}${itemStr},`);
      }
      lines.push(`${pad(indent)}]`);
      return lines.join("\n");
    }
    case "call": {
      const uidArg = JSON.stringify(node.uid);
      const callExpr = node.options === undefined
        ? `${node.name}(${uidArg})`
        : `${node.name}(${uidArg}, ${format(node.options, indent)})`;
      return node.comment ? `${node.comment}\n${callExpr}` : callExpr;
    }
  }
};

const extractFieldMetadata = (field: Record<string, any>): Record<string, unknown> | undefined => {
  const metadata = { ...(field.field_metadata ?? {}) } as Record<string, unknown>;
  delete metadata.description;
  delete metadata.multiline;
  delete metadata.markdown;
  delete metadata.allow_rich_text;
  delete metadata.allow_json_rte;
  delete metadata.rich_text_type;
  delete metadata.ref_multiple_content_types;

  return Object.keys(metadata).length > 0 ? metadata : undefined;
};

const extractCodegenErrorMessages = (field: Record<string, any>): Record<string, string> | undefined => {
  const raw = field.error_messages;
  if (!raw || typeof raw !== "object") return undefined;

  const entries = Object.entries(raw).filter(
    ([, value]) => typeof value === "string" && value.length > 0,
  ) as Array<[string, string]>;

  return entries.length > 0 ? Object.fromEntries(entries) : undefined;
};

const resolveBuilderName = (field: Record<string, any>): { builder: string; comment?: string | undefined } => {
  if (field.data_type === "text" && Array.isArray(field.enum?.choices) && field.enum.choices.length > 0) {
    return { builder: "enumField" };
  }

  if (field.data_type === "text" && field.field_metadata?.allow_rich_text) {
    return { builder: "richText" };
  }

  if (field.data_type === "text" && field.field_metadata?.markdown) {
    return { builder: "markdown" };
  }

  if (field.data_type === "json" && field.field_metadata?.allow_json_rte) {
    return { builder: "jsonRte" };
  }

  const builder = {
    text: "text",
    number: "number",
    boolean: "boolean",
    isodate: "date",
    json: "json",
    file: "file",
    link: "link",
    reference: "reference",
    group: "group",
    blocks: "modularBlocks",
    global_field: "globalField",
    taxonomy: "taxonomy",
  } as Record<string, string>;

  const resolvedBuilder = builder[field.data_type];

  if (resolvedBuilder) {
    return { builder: resolvedBuilder };
  }

  return {
    builder: "text",
    comment: `// Fallback for unsupported Contentstack field type "${String(field.data_type)}".`,
  };
};

const createBaseOptionEntries = (
  field: Record<string, any>,
  builder: string,
): Array<{ key: string; value: Node }> => {
  const entries: Array<{ key: string; value: Node }> = [];
  const displayName = field.display_name ?? field.uid;
  const expectedTitle = titleFromUid(field.uid);
  const metadata = extractFieldMetadata(field);
  const multiple = field.multiple;

  if (displayName && displayName !== expectedTitle) {
    entries.push({ key: "title", value: raw(JSON.stringify(displayName)) });
  }

  if (field.mandatory) {
    entries.push({ key: "required", value: raw("true") });
  }

  if (field.unique) {
    entries.push({ key: "unique", value: raw("true") });
  }

  if (field.non_localizable) {
    entries.push({ key: "nonLocalizable", value: raw("true") });
  }

  const shouldRenderMultiple =
    builder === "modularBlocks"
      ? multiple === false
      : builder === "taxonomy"
        ? multiple !== undefined
        : Boolean(multiple);

  if (shouldRenderMultiple) {
    entries.push({ key: "multiple", value: raw(String(Boolean(multiple))) });
  }

  if (field.field_metadata?.description) {
    entries.push({ key: "description", value: raw(JSON.stringify(field.field_metadata.description)) });
  }

  if (field.default_value !== undefined) {
    entries.push({ key: "defaultValue", value: jsonNode(field.default_value) });
  }

  const errorMessages = extractCodegenErrorMessages(field);
  // For text fields, .format is rendered separately via `formatErrorMessage`; skip it here.
  if (errorMessages) {
    const filtered = builder === "text"
      ? Object.fromEntries(Object.entries(errorMessages).filter(([key]) => key !== "format"))
      : errorMessages;

    if (Object.keys(filtered).length > 0) {
      entries.push({ key: "errorMessages", value: jsonNode(filtered) });
    }
  }

  if (metadata) {
    entries.push({ key: "metadata", value: jsonNode(metadata) });
  }

  return entries;
};

const collectBuilderImports = (fields: Record<string, any>[], imports = new Set<string>()): Set<string> => {
  for (const field of fields) {
    imports.add(resolveBuilderName(field).builder);

    if (Array.isArray(field.schema)) {
      collectBuilderImports(field.schema, imports);
    }

    if (Array.isArray(field.blocks)) {
      for (const block of field.blocks) {
        if (typeof block.reference_to === "string") continue;
        collectBuilderImports(block.schema ?? [], imports);
      }
    }
  }

  return imports;
};

const renderField = (field: Record<string, any>): Node => {
  const { builder, comment } = resolveBuilderName(field);
  const options = createBaseOptionEntries(field, builder);

  if (builder === "text") {
    if (field.field_metadata?.multiline) {
      options.push({ key: "multiline", value: raw("true") });
    }
    if (field.format) {
      options.push({ key: "format", value: raw(JSON.stringify(field.format)) });
    }
    if (field.error_messages?.format) {
      options.push({ key: "formatErrorMessage", value: raw(JSON.stringify(field.error_messages.format)) });
    }
  }

  if (builder === "date") {
    if (field.startDate !== undefined) {
      options.push({ key: "startDate", value: jsonNode(field.startDate) });
    }
    if (field.endDate !== undefined) {
      options.push({ key: "endDate", value: jsonNode(field.endDate) });
    }
  }

  if (builder === "reference") {
    options.push({ key: "to", value: jsonNode(field.reference_to ?? []) });
    if (typeof field.field_metadata?.ref_multiple_content_types === "boolean") {
      options.push({
        key: "refMultipleContentTypes",
        value: raw(String(field.field_metadata.ref_multiple_content_types)),
      });
    }
  }

  if (builder === "globalField") {
    options.push({ key: "ref", value: raw(JSON.stringify(field.reference_to)) });
  }

  if (builder === "file") {
    if (Array.isArray(field.extensions) && field.extensions.length > 0) {
      options.push({ key: "extensions", value: jsonNode(field.extensions) });
    }
  }

  if (builder === "enumField") {
    const advanced = field.enum?.advanced === true;
    const rawChoices = Array.isArray(field.enum?.choices) ? field.enum.choices : [];
    const choices = advanced
      ? rawChoices.map((choice: { key?: string; value?: string }) => ({
          key: typeof choice?.key === "string" ? choice.key : String(choice?.value ?? ""),
          value: typeof choice?.value === "string" ? choice.value : "",
        }))
      : rawChoices.map((choice: string | { value?: string }) =>
          typeof choice === "string" ? choice : choice?.value ?? "",
        );

    options.push({ key: "choices", value: jsonNode(choices) });
    if (advanced) {
      options.push({ key: "advanced", value: raw("true") });
    }
    if (field.display_type) {
      options.push({ key: "displayType", value: raw(JSON.stringify(field.display_type)) });
    }
    if (typeof field.min_instance === "number") {
      options.push({ key: "minInstance", value: raw(String(field.min_instance)) });
    }
    if (typeof field.max_instance === "number") {
      options.push({ key: "maxInstance", value: raw(String(field.max_instance)) });
    }
  }

  if (builder === "richText" || builder === "jsonRte") {
    const richTextType = field.field_metadata?.rich_text_type;
    if (richTextType && richTextType !== "advanced") {
      options.push({ key: "richTextType", value: raw(JSON.stringify(richTextType)) });
    }
  }

  if (builder === "jsonRte" && Array.isArray(field.reference_to) && field.reference_to.length > 0) {
    options.push({ key: "referenceTo", value: jsonNode(field.reference_to) });
  }

  if (builder === "jsonRte" && Array.isArray(field.plugins) && field.plugins.length > 0) {
    options.push({ key: "plugins", value: jsonNode(field.plugins) });
  }

  if (builder === "taxonomy") {
    options.push({ key: "taxonomies", value: jsonNode(field.taxonomies ?? []) });
  }

  if (builder === "group") {
    const nestedFields = arrayNode(
      (field.schema ?? []).map((nestedField: Record<string, any>) => renderField(nestedField)),
    );
    options.push({ key: "fields", value: nestedFields });
  }

  if (builder === "modularBlocks") {
    const blocks = (field.blocks ?? []).map((block: Record<string, any>): Node => {
      const baseEntries: Array<{ key: string; value: Node }> = [
        { key: "uid", value: raw(JSON.stringify(block.uid)) },
        { key: "title", value: raw(JSON.stringify(block.title ?? titleFromUid(block.uid))) },
      ];

      if (typeof block.reference_to === "string") {
        return objectNode([
          ...baseEntries,
          { key: "globalFieldRef", value: raw(JSON.stringify(block.reference_to)) },
        ]);
      }

      return objectNode([
        ...baseEntries,
        {
          key: "fields",
          value: arrayNode(
            (block.schema ?? []).map((nestedField: Record<string, any>) => renderField(nestedField)),
          ),
        },
      ]);
    });

    options.push({ key: "blocks", value: arrayNode(blocks) });
  }

  return {
    kind: "call",
    name: builder,
    uid: field.uid,
    options: options.length > 0 ? objectNode(options) : undefined,
    comment,
  };
};

const renderEntityFile = (
  definitionKind: "content_type" | "global_field",
  entity: Record<string, any>,
): string => {
  const builderImports = [...collectBuilderImports(entity.schema ?? [])].sort((left, right) =>
    left.localeCompare(right),
  );
  const factoryImport = definitionKind === "content_type" ? "defineContentType" : "defineGlobalField";
  const importList = [factoryImport, ...builderImports].join(", ");

  const fieldNodes = (entity.schema ?? []).map((field: Record<string, any>) => renderField(field));

  const entries: Array<{ key: string; value: Node }> = [
    { key: "title", value: raw(JSON.stringify(entity.title)) },
  ];

  if (entity.description) {
    entries.push({ key: "description", value: raw(JSON.stringify(entity.description)) });
  }

  entries.push({ key: "fields", value: arrayNode(fieldNodes) });

  if (definitionKind === "content_type" && entity.options && Object.keys(entity.options).length > 0) {
    entries.push({ key: "options", value: jsonNode(entity.options) });
  }

  const entityCall: Node = {
    kind: "call",
    name: factoryImport,
    uid: entity.uid,
    options: objectNode(entries),
  };

  return [
    GENERATED_HEADER,
    `import { ${importList} } from "@timbenniks/contentstack-stacksmith";`,
    "",
    `export default ${format(entityCall, 0)};`,
    "",
  ].join("\n");
};

const renderRegistryFile = (
  contentTypes: Record<string, any>[],
  globalFields: Record<string, any>[],
): string => {
  const globalFieldImports = globalFields.map((globalField) => ({
    symbol: globalField.uid,
    path: `./global-fields/${toKebabCase(globalField.uid)}`,
  }));
  const contentTypeImports = contentTypes.map((contentType) => ({
    symbol: contentType.uid,
    path: `./content-types/${toKebabCase(contentType.uid)}`,
  }));
  const importLines = [
    'import { defineModels } from "@timbenniks/contentstack-stacksmith";',
    "",
    ...globalFieldImports.map((entry) => `import ${entry.symbol} from "${entry.path}";`),
    ...contentTypeImports.map((entry) => `import ${entry.symbol} from "${entry.path}";`),
  ];

  return [
    GENERATED_HEADER,
    ...importLines,
    "",
    "export default defineModels({",
    `  contentTypes: [${contentTypeImports.map((entry) => entry.symbol).join(", ")}],`,
    `  globalFields: [${globalFieldImports.map((entry) => entry.symbol).join(", ")}],`,
    "});",
    "",
  ].join("\n");
};

const renderPackageJson = (packageName: string, modelsVersion: string, isMonorepo: boolean): string =>
  JSON.stringify(
    {
      name: packageName,
      private: true,
      version: "0.1.0",
      type: "module",
      scripts: {
        build: "tsc -p tsconfig.build.json --noEmit",
        typecheck: "tsc -p tsconfig.json --noEmit",
        lint: "eslint . --ext .ts",
        test: "vitest run --passWithNoTests",
        clean: "rimraf .contentstack",
        "build-models": "csdx stacksmith:build --cwd .",
        "plan-models": "csdx stacksmith:plan --cwd .",
        "diff-models": "csdx stacksmith:diff --cwd .",
        "docs-models": "csdx stacksmith:docs --cwd .",
      },
      dependencies: {
        "@timbenniks/contentstack-stacksmith": isMonorepo ? "workspace:*" : modelsVersion,
      },
    },
    null,
    2,
  ) + "\n";

const renderTsConfig = (): string =>
  JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "ESNext",
        moduleResolution: "Bundler",
        strict: true,
        esModuleInterop: true,
        allowSyntheticDefaultImports: true,
        forceConsistentCasingInFileNames: true,
        skipLibCheck: true,
        resolveJsonModule: true,
        declaration: true,
        sourceMap: true,
        noUncheckedIndexedAccess: true,
        exactOptionalPropertyTypes: true,
        useDefineForClassFields: true,
        outDir: "dist",
      },
      include: ["contentstack.stacksmith.config.ts", "src/**/*.ts"],
    },
    null,
    2,
  ) + "\n";

const renderTsConfigBuild = (): string =>
  JSON.stringify(
    {
      extends: "./tsconfig.json",
      compilerOptions: {
        composite: false,
        rootDir: "src",
        outDir: "dist",
      },
      include: ["src"],
    },
    null,
    2,
  ) + "\n";

const renderConfigFile = (projectName: string): string => [
  'import { defineModelsConfig } from "@timbenniks/contentstack-stacksmith";',
  "",
  "export default defineModelsConfig({",
  `  projectName: ${JSON.stringify(projectName)},`,
  "});",
  "",
].join("\n");

export class ImportCodegenService {
  generate(input: ImportCodegenInput): ImportCodegenResult {
    const contentTypes = [...input.contentTypes].sort((left, right) => left.uid.localeCompare(right.uid));
    const globalFields = [...input.globalFields].sort((left, right) => left.uid.localeCompare(right.uid));
    const modelsDir = dirname(input.modelsEntryPath);
    const contentTypesDir = join(modelsDir, "content-types");
    const globalFieldsDir = join(modelsDir, "global-fields");
    const files: GeneratedImportFile[] = [
      {
        path: relative(input.cwd, join(input.cwd, "package.json")),
        content: renderPackageJson(input.packageName, input.modelsVersion, input.isMonorepo ?? false),
        managed: false,
      },
      {
        path: relative(input.cwd, join(input.cwd, "tsconfig.json")),
        content: renderTsConfig(),
        managed: false,
      },
      {
        path: relative(input.cwd, join(input.cwd, "tsconfig.build.json")),
        content: renderTsConfigBuild(),
        managed: false,
      },
      {
        path: relative(input.cwd, input.configPath),
        content: renderConfigFile(input.projectName),
        managed: false,
      },
    ];

    for (const globalField of globalFields) {
      files.push({
        path: relative(input.cwd, join(globalFieldsDir, `${toKebabCase(globalField.uid)}.ts`)),
        content: renderEntityFile("global_field", globalField),
        managed: true,
      });
    }

    for (const contentType of contentTypes) {
      files.push({
        path: relative(input.cwd, join(contentTypesDir, `${toKebabCase(contentType.uid)}.ts`)),
        content: renderEntityFile("content_type", contentType),
        managed: true,
      });
    }

    files.push({
      path: relative(input.cwd, input.modelsEntryPath),
      content: renderRegistryFile(contentTypes, globalFields),
      managed: true,
    });

    return {
      files,
      managedFiles: files.filter((file) => file.managed).map((file) => file.path),
      contentTypeUids: contentTypes.map((contentType) => contentType.uid),
      globalFieldUids: globalFields.map((globalField) => globalField.uid),
    };
  }
}
