// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineGlobalField, enumField, link } from "@timbenniks/contentstack-stacksmith";

export default defineGlobalField("cta", {
  title: "Cta",
  description: "A link to anywhere",
  fields: [
    link("link", {
      metadata: {
        "default_value": {
          "title": "",
          "url": ""
        }
      },
    }),
    enumField("variant", {
      metadata: {
        "default_value": "PrimaryFillButton"
      },
      choices: [
        "ghost",
        "PrimaryFillButton",
        "SecondaryFillButton",
        "OpacityButton",
        "UnderlineButton",
        "ButtonContainer",
        "InlinePrimary",
        "InlineSecondary",
        "link",
        "DocSecondaryBorder",
        "DocWhiteSecondary",
        "DocsPrimaryFillButton"
      ],
      displayType: "dropdown",
    }),
  ],
});
