// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineGlobalField, modularBlocks, text } from "@timbenniks/contentstack-stacksmith";

export default defineGlobalField("faq", {
  title: "FAQ",
  description: "General FAQ for pages",
  fields: [
    modularBlocks("qas", {
      title: "QAs",
      metadata: {
        "instruction": ""
      },
      blocks: [
        {
          uid: "qa",
          title: "QA",
          fields: [
            text("question", {
              metadata: {
                "default_value": ""
              },
            }),
            text("answer", {
              metadata: {
                "default_value": ""
              },
              multiline: true,
            }),
          ],
        },
      ],
    }),
  ],
});
