// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineGlobalField, boolean, enumField, file, jsonRte, modularBlocks, text } from "@timbenniks/contentstack-stacksmith";

export default defineGlobalField("hero", {
  title: "Hero",
  description: "Page hero",
  fields: [
    text("title", {
      metadata: {
        "default_value": ""
      },
    }),
    enumField("title_tag", {
      metadata: {
        "default_value": "h1"
      },
      choices: [
        "h1",
        "h2",
        "h3",
        "p"
      ],
      displayType: "dropdown",
    }),
    enumField("title_variant", {
      metadata: {
        "default_value": "cs-h3"
      },
      choices: [
        "cs-h1-display",
        "h1-standard",
        "h1-compact",
        "h1-display-compact",
        "cs-h1-header",
        "cs-h1-3xl",
        "cs-h2",
        "cs-h3",
        "cs-h4",
        "cs-h5",
        "cs-h6",
        "hero-text",
        "section-heading"
      ],
      displayType: "dropdown",
    }),
    jsonRte("description", {
      metadata: {
        "embed_entry": false,
        "default_value": "",
        "options": [
          "undo",
          "redo",
          "bold",
          "underline",
          "italic",
          "deleted",
          "removeFormatting",
          "link"
        ],
        "max_height": "100"
      },
      richTextType: "custom",
      referenceTo: [
        "sys_assets"
      ],
    }),
    boolean("show_search", {
      metadata: {
        "default_value": false
      },
    }),
    modularBlocks("ctas", {
      metadata: {
        "instruction": ""
      },
      blocks: [
        {
          uid: "cta",
          title: "Cta",
          globalFieldRef: "cta",
        },
      ],
    }),
    modularBlocks("components", {
      metadata: {
        "instruction": ""
      },
      blocks: [
        {
          uid: "list",
          title: "List",
          globalFieldRef: "list",
        },
        {
          uid: "media",
          title: "Media",
          fields: [
            text("title", {
              metadata: {
                "default_value": ""
              },
            }),
            text("description", {
              metadata: {
                "default_value": ""
              },
              multiline: true,
            }),
            file("asset"),
          ],
        },
        {
          uid: "technology_list",
          title: "Technology List",
          globalFieldRef: "technology_list",
        },
      ],
    }),
  ],
});
