// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineGlobalField, boolean, enumField, file, group, jsonRte, link, modularBlocks, number, reference, text } from "@timbenniks/contentstack-stacksmith";

export default defineGlobalField("list", {
  title: "List",
  description: "A list of things",
  fields: [
    text("title", {
      metadata: {
        "default_value": ""
      },
    }),
    enumField("title_tag", {
      metadata: {
        "default_value": "h2"
      },
      choices: [
        "h1",
        "h2",
        "h3",
        "h4",
        "p"
      ],
      displayType: "dropdown",
    }),
    enumField("title_variant", {
      metadata: {
        "default_value": "cs-h3"
      },
      choices: [
        "cs-h1-display",
        "h1-standard",
        "h1-compact",
        "h1-display-compact",
        "cs-h1-header",
        "cs-h1-3xl",
        "cs-h2",
        "cs-h3",
        "cs-h4",
        "cs-h5",
        "cs-h6",
        "hero-text",
        "section-heading"
      ],
      displayType: "dropdown",
    }),
    jsonRte("description", {
      metadata: {
        "embed_entry": false,
        "default_value": "",
        "options": [
          "undo",
          "redo",
          "bold",
          "underline",
          "italic",
          "deleted",
          "lists",
          "removeFormatting",
          "link"
        ],
        "max_height": "100"
      },
      richTextType: "custom",
      referenceTo: [
        "sys_assets"
      ],
    }),
    link("view_all_link", {
      metadata: {
        "default_value": {
          "title": "",
          "url": ""
        }
      },
    }),
    number("columns", {
      metadata: {
        "default_value": ""
      },
    }),
    enumField("card_type", {
      metadata: {
        "default_value": "default"
      },
      choices: [
        "default",
        "icon"
      ],
      displayType: "dropdown",
    }),
    enumField("icon_variant", {
      metadata: {
        "default_value": "default"
      },
      choices: [
        "default",
        "centered"
      ],
      displayType: "dropdown",
    }),
    enumField("icon_size", {
      metadata: {
        "default_value": "default"
      },
      choices: [
        "default",
        "small"
      ],
      displayType: "dropdown",
    }),
    enumField("align", {
      metadata: {
        "default_value": "full"
      },
      choices: [
        "full",
        "left"
      ],
      displayType: "dropdown",
    }),
    modularBlocks("cards", {
      metadata: {
        "instruction": ""
      },
      blocks: [
        {
          uid: "card",
          title: "Card",
          fields: [
            text("title", {
              metadata: {
                "default_value": ""
              },
            }),
            text("description", {
              metadata: {
                "default_value": ""
              },
              multiline: true,
            }),
            file("image"),
            text("image_url", {
              title: "image_url",
              metadata: {
                "default_value": "",
                "instruction": "This is an alternative to the real image in case we don't upload an image."
              },
            }),
            link("link", {
              metadata: {
                "default_value": {
                  "title": "",
                  "url": ""
                }
              },
            }),
            text("import_from_link", {
              title: "Import from link",
              metadata: {
                "extension": true,
                "instruction": "Paste alink here and the card will be filled. Like Magic."
              },
            }),
          ],
        },
      ],
    }),
    reference("linked_cards", {
      metadata: {
        "ref_multiple": true
      },
      to: [
        "person",
        "page",
        "live_stream",
        "kickstart",
        "guide",
        "blogpost"
      ],
      refMultipleContentTypes: true,
    }),
    group("custom_card_query", {
      title: "Custom card query",
      metadata: {
        "instruction": ""
      },
      fields: [
        enumField("content_type", {
          metadata: {
            "default_value": ""
          },
          choices: [
            "page",
            "blogpost",
            "guide",
            "person",
            "live_stream",
            "kickstart"
          ],
          displayType: "dropdown",
        }),
        text("terms", {
          multiple: true,
          metadata: {
            "default_value": "",
            "isTitle": false
          },
        }),
        text("taxonomy_terms_selector", {
          metadata: {
            "extension": true
          },
        }),
        number("limit", {
          metadata: {
            "default_value": ""
          },
        }),
        enumField("order_by", {
          metadata: {
            "default_value": "date"
          },
          choices: [
            "date",
            "alphabetical"
          ],
          displayType: "dropdown",
        }),
        enumField("sort", {
          metadata: {
            "default_value": "DESC"
          },
          choices: [
            "DESC",
            "ASC"
          ],
          displayType: "radio",
        }),
        boolean("show_filters", {
          title: "Show filters",
          metadata: {
            "default_value": false
          },
        }),
      ],
    }),
  ],
});
