// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineGlobalField, group, link, text } from "@timbenniks/contentstack-stacksmith";

export default defineGlobalField("menu", {
  title: "Menu",
  fields: [
    text("title", {
      metadata: {
        "default_value": ""
      },
    }),
    group("links", {
      metadata: {
        "instruction": ""
      },
      fields: [
        link("link", {
          multiple: true,
          metadata: {
            "default_value": {
              "title": "",
              "url": ""
            },
            "isTitle": false
          },
        }),
      ],
    }),
  ],
});
