// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineGlobalField, boolean, enumField, file, json, text } from "@timbenniks/contentstack-stacksmith";

export default defineGlobalField("metadata", {
  title: "Metadata",
  description: "A group of fields for page meta",
  fields: [
    text("description", {
      metadata: {
        "default_value": ""
      },
      multiline: true,
    }),
    file("image"),
    text("canonical", {
      metadata: {
        "default_value": ""
      },
    }),
    boolean("block_robots", {
      title: "Block robots",
      metadata: {
        "default_value": false
      },
    }),
    boolean("include_in_sitemap", {
      title: "Include in sitemap",
      metadata: {
        "default_value": true
      },
    }),
    enumField("schema_type", {
      metadata: {
        "default_value": "WebPage"
      },
      choices: [
        "WebPage",
        "Article",
        "BlogPosting",
        "NewsArticle",
        "Product",
        "FAQPage",
        "HowTo",
        "Event",
        "Organization",
        "Person"
      ],
      displayType: "dropdown",
    }),
    json("custom_json_ld", {
      title: "Custom json-ld",
      metadata: {
        "extension": true
      },
    }),
  ],
});
