// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineGlobalField, boolean, link, modularBlocks, reference } from "@timbenniks/contentstack-stacksmith";

export default defineGlobalField("navigation", {
  title: "Navigation",
  description: "Generic Navigation",
  fields: [
    modularBlocks("links", {
      metadata: {
        "instruction": ""
      },
      blocks: [
        {
          uid: "link",
          title: "Link",
          fields: [
            boolean("open_in_new_tab", {
              title: "Open in new tab",
              metadata: {
                "default_value": false
              },
            }),
            link("link", {
              metadata: {
                "default_value": {
                  "title": "",
                  "url": ""
                }
              },
            }),
            reference("entry", {
              metadata: {
                "ref_multiple": false
              },
              to: [
                "page",
                "live_stream",
                "guide",
                "blogpost"
              ],
              refMultipleContentTypes: true,
            }),
          ],
        },
      ],
    }),
  ],
});
