// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineGlobalField, enumField, jsonRte, text } from "@timbenniks/contentstack-stacksmith";

export default defineGlobalField("notice", {
  title: "Notice",
  description: "General message",
  fields: [
    text("title", {
      metadata: {
        "default_value": ""
      },
    }),
    jsonRte("copy", {
      metadata: {
        "embed_entry": false,
        "default_value": "",
        "options": [
          "undo",
          "redo",
          "blockquote",
          "pre",
          "h3",
          "h4",
          "h5",
          "h6",
          "bold",
          "underline",
          "italic",
          "deleted",
          "removeFormatting",
          "link",
          "h2",
          "lists"
        ]
      },
      richTextType: "custom",
      referenceTo: [
        "sys_assets"
      ],
    }),
    enumField("type", {
      metadata: {
        "default_value": "notice"
      },
      choices: [
        "notice",
        "quick-tip",
        "warning",
        "error"
      ],
      displayType: "dropdown",
    }),
  ],
});
