// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineGlobalField, boolean, enumField, jsonRte, text } from "@timbenniks/contentstack-stacksmith";

export default defineGlobalField("rich_text", {
  title: "Rich Text",
  description: "Title and text: anywhere",
  fields: [
    text("title", {
      metadata: {
        "default_value": ""
      },
    }),
    enumField("title_tag", {
      metadata: {
        "default_value": "h2"
      },
      choices: [
        "h1",
        "h2",
        "h3",
        "h4",
        "p"
      ],
      displayType: "dropdown",
    }),
    enumField("title_variant", {
      metadata: {
        "default_value": ""
      },
      choices: [
        "cs-h1-display",
        "h1-standard",
        "h1-compact",
        "h1-display-compact",
        "cs-h1-header",
        "cs-h1-3xl",
        "cs-h2",
        "cs-h3",
        "cs-h4",
        "cs-h5",
        "cs-h6",
        "hero-text",
        "section-heading"
      ],
      displayType: "dropdown",
    }),
    boolean("fancy_background", {
      metadata: {
        "default_value": false
      },
    }),
    jsonRte("copy", {
      metadata: {
        "embed_entry": false,
        "default_value": "",
        "options": [
          "undo",
          "redo",
          "blockquote",
          "pre",
          "h2",
          "h3",
          "h5",
          "h4",
          "h6",
          "bold",
          "underline",
          "italic",
          "deleted",
          "inlinecode",
          "lists",
          "removeFormatting",
          "video",
          "imagemanager",
          "link",
          "alignment",
          "indentation",
          "table"
        ]
      },
      richTextType: "custom",
      referenceTo: [
        "sys_assets"
      ],
    }),
  ],
});
