// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineGlobalField, enumField, number, reference, text } from "@timbenniks/contentstack-stacksmith";

export default defineGlobalField("technology_list", {
  title: "Technology List",
  description: "Specifically for entries with an icon field like Kickstarts",
  fields: [
    text("title", {
      metadata: {
        "default_value": ""
      },
    }),
    enumField("title_tag", {
      metadata: {
        "default_value": "p"
      },
      choices: [
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "p"
      ],
      displayType: "dropdown",
    }),
    enumField("title_variant", {
      title: "Title variant",
      metadata: {
        "default_value": "cs-h3"
      },
      choices: [
        "cs-h1-display",
        "h1-standard",
        "h1-compact",
        "h1-display-compact",
        "cs-h1-header",
        "cs-h1-3xl",
        "cs-h2",
        "cs-h3",
        "cs-h4",
        "cs-h5",
        "cs-h6",
        "hero-text",
        "section-heading"
      ],
      displayType: "dropdown",
    }),
    number("columns", {
      metadata: {
        "default_value": 4
      },
    }),
    reference("items", {
      title: "items",
      metadata: {
        "ref_multiple": true
      },
      to: [
        "kickstart"
      ],
      refMultipleContentTypes: true,
    }),
  ],
});
