// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineGlobalField, enumField, modularBlocks, text } from "@timbenniks/contentstack-stacksmith";

export default defineGlobalField("two_column", {
  title: "Two Column",
  fields: [
    text("title", {
      metadata: {
        "default_value": ""
      },
    }),
    enumField("title_tag", {
      title: "Title tag",
      metadata: {
        "default_value": ""
      },
      choices: [
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "p"
      ],
      displayType: "dropdown",
    }),
    text("description", {
      metadata: {
        "default_value": ""
      },
      multiline: true,
    }),
    modularBlocks("side_a", {
      metadata: {
        "instruction": ""
      },
      blocks: [
        {
          uid: "rich_text",
          title: "Rich text",
          globalFieldRef: "rich_text",
        },
        {
          uid: "list",
          title: "List",
          globalFieldRef: "list",
        },
        {
          uid: "technology_list",
          title: "Technology List",
          globalFieldRef: "technology_list",
        },
      ],
    }),
    modularBlocks("side_b", {
      metadata: {
        "instruction": ""
      },
      blocks: [
        {
          uid: "rich_text",
          title: "Rich Text",
          globalFieldRef: "rich_text",
        },
        {
          uid: "list",
          title: "List",
          globalFieldRef: "list",
        },
        {
          uid: "technology_list",
          title: "Technology List",
          globalFieldRef: "technology_list",
        },
      ],
    }),
  ],
});
