// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineContentType, date, globalField, modularBlocks, reference, taxonomy, text } from "@timbenniks/contentstack-stacksmith";

export default defineContentType("blogpost", {
  title: "Blogpost",
  description: "Thought leadership and research",
  fields: [
    text("title", {
      required: true,
      unique: true,
      metadata: {
        "_default": true,
        "version": 3
      },
    }),
    text("url", {
      title: "URL",
      metadata: {
        "_default": true,
        "version": 3
      },
    }),
    reference("author", {
      metadata: {
        "ref_multiple": true,
        "default_value": null
      },
      to: [
        "person"
      ],
      refMultipleContentTypes: true,
    }),
    date("date", {
      description: "If this entry was created at another time, fill out this field. If not filled, we use the default CMS creation date.",
      metadata: {
        "default_value": {
          "custom": false,
          "date": "",
          "time": ""
        }
      },
      startDate: null,
      endDate: null,
    }),
    taxonomy("taxonomies", {
      title: "Taxonomy",
      multiple: true,
      metadata: {
        "default_value": ""
      },
      taxonomies: [
        {
          "taxonomy_uid": "subjects",
          "mandatory": false,
          "multiple": true,
          "non_localizable": false
        },
        {
          "taxonomy_uid": "technology",
          "mandatory": false,
          "multiple": true,
          "non_localizable": false
        }
      ],
    }),
    modularBlocks("additional_items", {
      metadata: {
        "instruction": "",
        "isTab": true
      },
      blocks: [
        {
          uid: "faq",
          title: "FAQ",
          globalFieldRef: "faq",
        },
        {
          uid: "notice",
          title: "Notice",
          globalFieldRef: "notice",
        },
        {
          uid: "related_items",
          title: "Related Items",
          globalFieldRef: "list",
        },
      ],
    }),
    globalField("metadata", {
      metadata: {
        "isTab": true
      },
      ref: "metadata",
    }),
    globalField("blog_content", {
      ref: "rich_text",
    }),
  ],
  options: {
    "is_page": true,
    "singleton": false,
    "sub_title": [],
    "title": "title",
    "url_pattern": "/blog/:title",
    "url_prefix": "/"
  },
});
