// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineContentType, globalField, group, text } from "@timbenniks/contentstack-stacksmith";

export default defineContentType("footer", {
  title: "Footer",
  fields: [
    text("title", {
      required: true,
      unique: true,
      metadata: {
        "_default": true,
        "version": 3
      },
    }),
    group("menus", {
      metadata: {
        "instruction": ""
      },
      fields: [
        globalField("menu", {
          multiple: true,
          ref: "menu",
        }),
      ],
    }),
  ],
  options: {
    "is_page": false,
    "singleton": true,
    "sub_title": [],
    "title": "title"
  },
});
