// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineContentType, boolean, globalField, link, text } from "@timbenniks/contentstack-stacksmith";

export default defineContentType("header", {
  title: "Header",
  description: "Global header",
  fields: [
    text("title", {
      required: true,
      unique: true,
      metadata: {
        "_default": true,
        "version": 3
      },
    }),
    boolean("show_search", {
      metadata: {
        "default_value": false
      },
    }),
    link("announcement", {
      metadata: {
        "default_value": {
          "title": "",
          "url": ""
        }
      },
    }),
    globalField("announcement_navigation", {
      title: "Announcement navigation",
      ref: "navigation",
    }),
    globalField("main_navigation", {
      ref: "navigation",
    }),
  ],
  options: {
    "is_page": false,
    "singleton": true,
    "sub_title": [],
    "title": "title"
  },
});
