// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineContentType, file, globalField, group, link, modularBlocks, taxonomy, text } from "@timbenniks/contentstack-stacksmith";

export default defineContentType("kickstart", {
  title: "Kickstart",
  description: "Kickstart landing pages",
  fields: [
    text("title", {
      required: true,
      unique: true,
      metadata: {
        "_default": true,
        "version": 3
      },
    }),
    text("url", {
      title: "URL",
      metadata: {
        "_default": true,
        "version": 3
      },
    }),
    file("icon"),
    taxonomy("taxonomies", {
      title: "Taxonomy",
      multiple: true,
      metadata: {
        "default_value": ""
      },
      taxonomies: [
        {
          "taxonomy_uid": "subjects",
          "mandatory": false,
          "multiple": true,
          "non_localizable": false
        },
        {
          "taxonomy_uid": "technology",
          "mandatory": false,
          "multiple": true,
          "non_localizable": false
        }
      ],
    }),
    group("kickstarter_links", {
      metadata: {
        "instruction": ""
      },
      fields: [
        link("documentation_link", {
          metadata: {
            "default_value": {
              "title": "Documentation",
              "url": ""
            }
          },
        }),
        link("demo_link", {
          metadata: {
            "default_value": {
              "title": "Demo",
              "url": ""
            }
          },
        }),
        link("installation_link", {
          metadata: {
            "default_value": {
              "title": "Install from Marketplace",
              "url": ""
            },
            "instruction": "Example: https://eu-app.contentstack.com/#!/marketplace?uid=blt5566e7ebe53e569d&type=starter"
          },
        }),
        link("sourcecode_link", {
          metadata: {
            "default_value": {
              "title": "Source code",
              "url": ""
            }
          },
        }),
      ],
    }),
    globalField("metadata", {
      metadata: {
        "isTab": true
      },
      ref: "metadata",
    }),
    globalField("kickstart_content", {
      ref: "rich_text",
    }),
    modularBlocks("components", {
      metadata: {
        "instruction": ""
      },
      blocks: [
        {
          uid: "rich_text",
          title: "Rich Text",
          globalFieldRef: "rich_text",
        },
        {
          uid: "list",
          title: "List",
          globalFieldRef: "list",
        },
        {
          uid: "notice",
          title: "Notice",
          globalFieldRef: "notice",
        },
        {
          uid: "two_column",
          title: "Two Column",
          globalFieldRef: "two_column",
        },
      ],
    }),
    modularBlocks("additional_items", {
      metadata: {
        "instruction": "",
        "isTab": true
      },
      blocks: [
        {
          uid: "notice",
          title: "Notice",
          globalFieldRef: "notice",
        },
        {
          uid: "faq",
          title: "faq",
          globalFieldRef: "faq",
        },
        {
          uid: "related_items",
          title: "Related Items",
          globalFieldRef: "list",
        },
      ],
    }),
  ],
  options: {
    "is_page": true,
    "singleton": false,
    "sub_title": [],
    "title": "title",
    "url_pattern": "/:title",
    "url_prefix": "/kickstarts/"
  },
});
