// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineContentType, date, globalField, modularBlocks, reference, taxonomy, text } from "@timbenniks/contentstack-stacksmith";

export default defineContentType("live_stream", {
  title: "Live Stream",
  description: "Live streams for devs",
  fields: [
    text("title", {
      required: true,
      unique: true,
      metadata: {
        "_default": true,
        "version": 3
      },
    }),
    text("url", {
      title: "URL",
      required: true,
      metadata: {
        "_default": true,
        "version": 3
      },
    }),
    date("date", {
      description: "If this entry was created at another time, fill out this field. If not filled, we use the default CMS creation date.",
      metadata: {
        "default_value": {
          "custom": false,
          "date": "",
          "time": ""
        }
      },
      startDate: null,
      endDate: null,
    }),
    taxonomy("taxonomies", {
      title: "Taxonomy",
      multiple: true,
      metadata: {
        "default_value": ""
      },
      taxonomies: [
        {
          "taxonomy_uid": "subjects",
          "mandatory": false,
          "multiple": true,
          "non_localizable": false
        },
        {
          "taxonomy_uid": "technology",
          "mandatory": false,
          "multiple": true,
          "non_localizable": false
        }
      ],
    }),
    reference("host", {
      metadata: {
        "ref_multiple": true,
        "default_value": null
      },
      to: [
        "person"
      ],
      refMultipleContentTypes: true,
    }),
    reference("guest", {
      metadata: {
        "ref_multiple": true,
        "default_value": null
      },
      to: [
        "person"
      ],
      refMultipleContentTypes: true,
    }),
    modularBlocks("additional_items", {
      metadata: {
        "instruction": "",
        "isTab": true
      },
      blocks: [
        {
          uid: "faq",
          title: "FAQ",
          globalFieldRef: "faq",
        },
        {
          uid: "notice",
          title: "Notice",
          globalFieldRef: "notice",
        },
        {
          uid: "related_items",
          title: "Related Items",
          globalFieldRef: "list",
        },
      ],
    }),
    globalField("metadata", {
      required: true,
      metadata: {
        "instruction": "Metadata for pages",
        "isTab": true
      },
      ref: "metadata",
    }),
    text("youtube_video_id", {
      title: "Youtube Video ID",
      metadata: {
        "default_value": "",
        "version": 3
      },
    }),
    modularBlocks("components", {
      metadata: {
        "instruction": ""
      },
      blocks: [
        {
          uid: "hero",
          title: "Hero",
          globalFieldRef: "hero",
        },
        {
          uid: "list",
          title: "List",
          globalFieldRef: "list",
        },
        {
          uid: "rich_text",
          title: "Rich Text",
          globalFieldRef: "rich_text",
        },
        {
          uid: "notice",
          title: "Notice",
          globalFieldRef: "notice",
        },
      ],
    }),
  ],
  options: {
    "is_page": true,
    "singleton": false,
    "sub_title": [],
    "title": "title",
    "url_pattern": "/:title",
    "url_prefix": "/livestreams/"
  },
});
