// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineContentType, globalField, modularBlocks, text } from "@timbenniks/contentstack-stacksmith";

export default defineContentType("page", {
  title: "Page",
  description: "A generic page content type suitable for most page usecases",
  fields: [
    text("title", {
      required: true,
      unique: true,
      metadata: {
        "_default": true,
        "version": 3
      },
    }),
    text("url", {
      title: "URL",
      required: true,
      metadata: {
        "_default": true,
        "version": 3
      },
    }),
    modularBlocks("additional_items", {
      metadata: {
        "instruction": "",
        "isTab": true
      },
      blocks: [
        {
          uid: "faq",
          title: "FAQ",
          globalFieldRef: "faq",
        },
        {
          uid: "notice",
          title: "Notice",
          globalFieldRef: "notice",
        },
        {
          uid: "related_items",
          title: "Related Items",
          globalFieldRef: "list",
        },
      ],
    }),
    globalField("metadata", {
      required: true,
      metadata: {
        "instruction": "Metadata for pages",
        "isTab": true
      },
      ref: "metadata",
    }),
    modularBlocks("components", {
      metadata: {
        "instruction": "",
        "isTab": true
      },
      blocks: [
        {
          uid: "hero",
          title: "Hero",
          globalFieldRef: "hero",
        },
        {
          uid: "list",
          title: "List",
          globalFieldRef: "list",
        },
        {
          uid: "rich_text",
          title: "Rich Text",
          globalFieldRef: "rich_text",
        },
        {
          uid: "notice",
          title: "Notice",
          globalFieldRef: "notice",
        },
        {
          uid: "two_column",
          title: "Two Column",
          globalFieldRef: "two_column",
        },
      ],
    }),
  ],
  options: {
    "is_page": true,
    "singleton": false,
    "sub_title": [],
    "title": "title",
    "url_pattern": "/:title",
    "url_prefix": "/"
  },
});
