// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineContentType, globalField, jsonRte, text } from "@timbenniks/contentstack-stacksmith";

export default defineContentType("person", {
  title: "Person",
  description: "A person",
  fields: [
    text("title", {
      required: true,
      unique: true,
      metadata: {
        "_default": true,
        "version": 3
      },
    }),
    text("url", {
      title: "URL",
      metadata: {
        "_default": true,
        "version": 3
      },
    }),
    jsonRte("bio", {
      metadata: {
        "embed_entry": false,
        "default_value": "",
        "options": [
          "undo",
          "redo",
          "bold",
          "underline",
          "italic",
          "deleted",
          "lists",
          "link"
        ]
      },
      richTextType: "custom",
      referenceTo: [
        "sys_assets"
      ],
    }),
    text("job", {
      metadata: {
        "default_value": "",
        "version": 3
      },
    }),
    globalField("metadata", {
      metadata: {
        "isTab": true
      },
      ref: "metadata",
    }),
  ],
  options: {
    "is_page": true,
    "singleton": false,
    "sub_title": [],
    "title": "title",
    "url_pattern": "/:title",
    "url_prefix": "/person/"
  },
});
