import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { basename, join, resolve } from "node:path";

import { expect } from "chai";
import { runCommand } from "@oclif/test";
import { Command as ContentstackCommand } from "@contentstack/cli-command";

import { createImportFetchMock } from "../helpers/import-fixtures";

describe("stacksmith:import", () => {
  const pluginRoot = resolve(__dirname, "../..");
  const appsRoot = resolve(pluginRoot, "../../apps");
  const originalFetch = globalThis.fetch;
  const prototype = ContentstackCommand.prototype as unknown as {
    getToken?: unknown;
    region?: unknown;
    cmaHost?: unknown;
    cdaHost?: unknown;
    cmaAPIUrl?: unknown;
    cdaAPIUrl?: unknown;
    uiHost?: unknown;
  };
  const originalDescriptors = {
    getToken: Object.getOwnPropertyDescriptor(ContentstackCommand.prototype, "getToken"),
    region: Object.getOwnPropertyDescriptor(ContentstackCommand.prototype, "region"),
    cmaHost: Object.getOwnPropertyDescriptor(ContentstackCommand.prototype, "cmaHost"),
    cdaHost: Object.getOwnPropertyDescriptor(ContentstackCommand.prototype, "cdaHost"),
    cmaAPIUrl: Object.getOwnPropertyDescriptor(ContentstackCommand.prototype, "cmaAPIUrl"),
    cdaAPIUrl: Object.getOwnPropertyDescriptor(ContentstackCommand.prototype, "cdaAPIUrl"),
    uiHost: Object.getOwnPropertyDescriptor(ContentstackCommand.prototype, "uiHost"),
  };

  const createTempAppDir = (): string => mkdtempSync(join(appsRoot, "import-test-"));

  beforeEach(() => {
    globalThis.fetch = createImportFetchMock();
    Object.defineProperty(ContentstackCommand.prototype, "getToken", {
      configurable: true,
      value: () => ({ authtoken: "test-management-token" }),
    });
    Object.defineProperty(ContentstackCommand.prototype, "region", {
      configurable: true,
      get: () => ({ name: "NA" }),
    });
    Object.defineProperty(ContentstackCommand.prototype, "cmaHost", {
      configurable: true,
      get: () => "api.contentstack.io",
    });
    Object.defineProperty(ContentstackCommand.prototype, "cdaHost", {
      configurable: true,
      get: () => "cdn.contentstack.io",
    });
    Object.defineProperty(ContentstackCommand.prototype, "cmaAPIUrl", {
      configurable: true,
      get: () => "https://api.contentstack.io",
    });
    Object.defineProperty(ContentstackCommand.prototype, "cdaAPIUrl", {
      configurable: true,
      get: () => "https://cdn.contentstack.io",
    });
    Object.defineProperty(ContentstackCommand.prototype, "uiHost", {
      configurable: true,
      get: () => "https://app.contentstack.com",
    });
  });

  afterEach(() => {
    globalThis.fetch = originalFetch;
    for (const [key, descriptor] of Object.entries(originalDescriptors)) {
      if (descriptor) {
        Object.defineProperty(ContentstackCommand.prototype, key, descriptor);
      } else {
        delete prototype[key as keyof typeof prototype];
      }
    }
  });

  it("imports a stack into an empty project directory", async () => {
    const appDir = createTempAppDir();

    try {
      const result = await runCommand(
        [
          "stacksmith:import",
          "--cwd",
          appDir,
          "--stack",
          "blt123",
          "--token-alias",
          "my-stack",
        ],
        { root: pluginRoot },
      );

      expect(result.error).to.equal(undefined);
      expect(readFileSync(join(appDir, "package.json"), "utf-8")).to.contain('"name": "import-test-');
      expect(readFileSync(join(appDir, "contentstack.stacksmith.config.ts"), "utf-8")).to.contain('defineModelsConfig');
      expect(readFileSync(join(appDir, "src/models/index.ts"), "utf-8")).to.contain("Generated by csdx stacksmith:import");
      expect(readFileSync(join(appDir, "src/models/content-types/article.ts"), "utf-8")).to.contain('enumField("status"');
      expect(readFileSync(join(appDir, ".contentstack/models/import-manifest.json"), "utf-8")).to.contain('"sourceStackApiKey": "blt123"');
    } finally {
      rmSync(appDir, { recursive: true, force: true });
    }
  });

  it("fails to refresh an existing import without --force", async () => {
    const appDir = createTempAppDir();

    try {
      await runCommand(
        [
          "stacksmith:import",
          "--cwd",
          appDir,
          "--stack",
          "blt123",
          "--token-alias",
          "my-stack",
        ],
        { root: pluginRoot },
      );

      const result = await runCommand(
        [
          "stacksmith:import",
          "--cwd",
          appDir,
          "--stack",
          "blt123",
          "--token-alias",
          "my-stack",
        ],
        { root: pluginRoot },
      );

      expect(result.error?.message ?? result.stderr).to.contain("Re-run with --force");
    } finally {
      rmSync(appDir, { recursive: true, force: true });
    }
  });

  it("refreshes an existing import with --force", async () => {
    const appDir = createTempAppDir();

    try {
      await runCommand(
        [
          "stacksmith:import",
          "--cwd",
          appDir,
          "--stack",
          "blt123",
          "--token-alias",
          "my-stack",
        ],
        { root: pluginRoot },
      );

      const articlePath = join(appDir, "src/models/content-types/article.ts");
      writeFileSync(articlePath, "export default null;\n");

      const result = await runCommand(
        [
          "stacksmith:import",
          "--cwd",
          appDir,
          "--stack",
          "blt123",
          "--token-alias",
          "my-stack",
          "--force",
        ],
        { root: pluginRoot },
      );

      expect(result.error).to.equal(undefined);
      expect(readFileSync(articlePath, "utf-8")).to.contain('defineContentType("article"');
    } finally {
      rmSync(appDir, { recursive: true, force: true });
    }
  });

  it("refuses to delete manifest-managed files outside the target project", async () => {
    const appDir = createTempAppDir();
    const sentinelPath = join(appsRoot, `${basename(appDir)}-sentinel.txt`);
    const articlePath = join(appDir, "src/models/content-types/article.ts");

    try {
      await runCommand(
        [
          "stacksmith:import",
          "--cwd",
          appDir,
          "--stack",
          "blt123",
          "--token-alias",
          "my-stack",
        ],
        { root: pluginRoot },
      );

      writeFileSync(sentinelPath, "do not delete\n");

      const manifestPath = join(appDir, ".contentstack/models/import-manifest.json");
      const manifest = JSON.parse(readFileSync(manifestPath, "utf-8")) as { generatedFiles: string[] };
      manifest.generatedFiles = ["../" + basename(sentinelPath)];
      writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + "\n");
      writeFileSync(articlePath, "export default null;\n");

      await runCommand(
        [
          "stacksmith:import",
          "--cwd",
          appDir,
          "--stack",
          "blt123",
          "--token-alias",
          "my-stack",
          "--force",
        ],
        { root: pluginRoot },
      );

      expect(existsSync(sentinelPath)).to.equal(true);
      expect(readFileSync(sentinelPath, "utf-8")).to.equal("do not delete\n");
      expect(readFileSync(articlePath, "utf-8")).to.equal("export default null;\n");
    } finally {
      rmSync(appDir, { recursive: true, force: true });
      rmSync(sentinelPath, { force: true });
    }
  });

  it("returns machine-readable JSON output", async () => {
    const appDir = createTempAppDir();

    try {
      const result = await runCommand(
        [
          "stacksmith:import",
          "--cwd",
          appDir,
          "--stack",
          "blt123",
          "--token-alias",
          "my-stack",
          "--json",
        ],
        { root: pluginRoot },
      );

      expect(result.error).to.equal(undefined);
      const payload = JSON.parse(result.stdout) as {
        generatedFiles: string[];
        contentTypeUids: string[];
        globalFieldUids: string[];
      };

      expect(payload.generatedFiles).to.include("src/models/index.ts");
      expect(payload.contentTypeUids).to.deep.equal(["article", "author"]);
      expect(payload.globalFieldUids).to.deep.equal(["seo"]);
    } finally {
      rmSync(appDir, { recursive: true, force: true });
    }
  });

  it("shows help output", async () => {
    const result = await runCommand(["stacksmith:import", "--help"], { root: pluginRoot });

    expect(result.stdout).to.contain("Import content types and global fields");
    expect(result.stdout).to.contain("--force");
  });
});
