// Generated by csdx stacksmith:import. Manual edits may be overwritten.


import { defineModels } from "@timbenniks/contentstack-stacksmith";

import cta from "./global-fields/cta";
import faq from "./global-fields/faq";
import hero from "./global-fields/hero";
import list from "./global-fields/list";
import menu from "./global-fields/menu";
import metadata from "./global-fields/metadata";
import navigation from "./global-fields/navigation";
import notice from "./global-fields/notice";
import rich_text from "./global-fields/rich-text";
import technology_list from "./global-fields/technology-list";
import two_column from "./global-fields/two-column";
import blogpost from "./content-types/blogpost";
import footer from "./content-types/footer";
import guide from "./content-types/guide";
import header from "./content-types/header";
import kickstart from "./content-types/kickstart";
import live_stream from "./content-types/live-stream";
import page from "./content-types/page";
import person from "./content-types/person";

export default defineModels({
  contentTypes: [blogpost, footer, guide, header, kickstart, live_stream, page, person],
  globalFields: [cta, faq, hero, list, menu, metadata, navigation, notice, rich_text, technology_list, two_column],
});
